name: testpr_env
channels:
  - robostack
  - robostack-staging
  - conda-forge
dependencies:
  - python 3.9.*
  - pip
  - boa
  - rospkg
  - catkin_pkg >=0.4.16
  - ruamel.yaml >=0.16.6
  - rosdistro >=0.8.0
  - empy >=3.3.4
