# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  tbb-devel:
    max_pin: x.x

console_bridge:
  - 1.0
gazebo:
  - '11'
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.19
ogre:
  - 1.10.12
pcl:
  - 1.12.0
# tbb pinned on Windows due to https://stackoverflow.com/questions/64510477/error-c2061-syntax-error-identifier-concurrent-vectortemplate-type-paramet
# tbb pinned on Unix due to https://github.com/conda-forge/gazebo-feedstock/issues/57
tbb:
  - 2019.9  # [win]
  - 2020.2  # [not win]
tbb_devel:
  - 2019.9  # [win]
  - 2020.2  # [not win]
libpqxx:
  - 6

python:
  # part of a zip_keys: python, python_impl, numpy
  # - 3.6.* *_cpython    # [not (osx and arm64)]
  # - 3.7.* *_cpython    # [not (osx and arm64)]
  # - 3.8.* *_cpython
  - 3.9.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  # - cpython   # [not (osx and arm64)]
  # - cpython   # [not (osx and arm64)]
  - cpython

# Project overrides
macos_min_version:             # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.14                      # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk  # [osx and arm64]

# fix build metadata, needed for mapviz
replacements:
  all_replacements:
    - tag: 'pkg-config build metadata'
      glob_patterns:
        - '*.pc'
      regex_re: '(?:-L|-I)?\"?([^;\s]+\/sysroot\/)'
      replacement_re: '$(CONDA_BUILD_SYSROOT_S)'
      regex_rg: '([^;\s"]+/sysroot/)'
    - tag: 'CMake build metadata'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/sysroot)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
    - tag: 'CMake build metadata OSX'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/MacOSX\d*\.?\d*\.sdk)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'

