# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2017                     # [win]
c_compiler_version:            # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2017                     # [win]
cxx_compiler_version:          # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 11                         # [osx and arm64]
  - 9                          # [osx and x86_64]
  - 9                          # [linux]
  - 5                          # [win64]
m2w64_c_compiler:              # [win]
  - m2w64-toolchain            # [win]
m2w64_cxx_compiler:            # [win]
  - m2w64-toolchain            # [win]
m2w64_fortran_compiler:        # [win]
  - m2w64-toolchain            # [win]
CMAKE_GENERATOR:               # [win]
  - NMake Makefiles            # [win]

_libgcc_mutex:
  - 0.1 conda_forge
#
# Go Compiler Options
#

# The basic go-compiler with CGO disabled,
# It generates fat binaries without libc dependencies
# The activation scripts will set your CC,CXX and related flags
# to invalid values.
go_compiler:
  - go-nocgo
# The go compiler build with CGO enabled.
# It can generate fat binaries that depend on conda's libc.
# You should use this compiler if the underlying
# program needs to link against other C libraries, in which
# case make sure to add  'c,cpp,fortran_compiler' for unix
# and the m2w64 equivalent for windows.
cgo_compiler:
  - go-cgo
# The following are helpful variables to simplify go meta.yaml files.
target_goos:
  - linux                      # [linux]
  - darwin                     # [osx]
  - windows                    # [win]
target_goarch:
  - amd64                      # [x86_64]
target_goexe:
  -                            # [unix]
  - .exe                       # [win]
target_gobin:
  - '${PREFIX}/bin/'           # [unix]
  - '%PREFIX%\bin\'            # [win]

# Rust Compiler Options
rust_compiler:
  - rust

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
target_platform:               # [win]
  - win-64                     # [win]
VERBOSE_AT:
  - V=1
VERBOSE_CM:
  - VERBOSE=1

# dual build configuration
channel_sources:
  - conda-forge,defaults                        # [not (aarch64 or armv7l or (osx and arm64))]
  - conda-forge/label/rust_dev,conda-forge      # [osx and arm64]
  - conda-forge                                 # [aarch64]
  - conda-forge,c4armv7l,defaults               # [armv7l]

channel_targets:
  - conda-forge main

cdt_name:  # [os.environ.get("BUILD_PLATFORM", "").startswith("linux") or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux)]
  - cos6   # [os.environ.get("BUILD_PLATFORM") == "linux-64" or (os.environ.get("CONFIG_VERSION", "1") == "1" and linux64)]
  - cos7   # [os.environ.get("BUILD_PLATFORM") == "linux-aarch64" or (os.environ.get("CONFIG_VERSION", "1") == "1" and aarch64)]
  - cos7   # [os.environ.get("BUILD_PLATFORM") == "linux-ppc64le" or (os.environ.get("CONFIG_VERSION", "1") == "1" and ppc64le)]
  - cos7   # [os.environ.get("BUILD_PLATFORM") == "linux-armv7l" or (os.environ.get("CONFIG_VERSION", "1") == "1" and armv7l)]

  # - cos6   # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
  # - cos6   # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
  # - cos6   # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]
  # - cos6   # [linux64 and (os.environ.get("BUILD_PLATFORM") == "linux-64" or os.environ.get("CONFIG_VERSION", "1") == "1")]

zip_keys:
  -                             # [unix]
    - c_compiler_version        # [unix]
    - cxx_compiler_version      # [unix]
    - fortran_compiler_version  # [unix]
  -
    - python
    - numpy
    - python_impl

# aarch64 specifics because conda-build sets many things to centos 6
# this can probably be removed when conda-build gets updated defaults
# for aarch64
cdt_arch: aarch64                       # [aarch64]
BUILD: aarch64-conda_cos7-linux-gnu     # [aarch64]

# armv7l specifics because conda-build sets many things to centos 6
# this can probably be removed when conda-build gets updated defaults
# for aarch64
cdt_arch: armv7l                          # [armv7l]
BUILD: armv7-conda_cos7-linux-gnueabihf   # [armv7l]

# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost_cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  cudnn:
    max_pin: x
    min_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  expat:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  fftw:
    max_pin: x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gazebo:
    max_pin: x
  gdal:
    max_pin: x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg_turbo:
    max_pin: x
  json_c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libmatio:
    max_pin: x.x
  libpcap:
    max_pin: x.x
  libpng:
    max_pin: x.x
  librdkafka:
    max_pin: x.x.x
  librsvg:
    max_pin: x
  libsvm:
    max_pin: x.x
  libtiff:
    max_pin: x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  log4cxx:
    max_pin: x.x.x
  lz4_c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf_cxx4:
    max_pin: x.x
  netcdf_fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  opencv:
    max_pin: x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  pcl:
    max_pin: x.x.x
  perl:
    max_pin: x.x.x
  poppler:
    max_pin: x.x
  qt:
    max_pin: x.x
  readline:
    max_pin: x
  r_base:
    max_pin: x.x
    min_pin: x.x
  sox:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  tiledb:
    max_pin: x.x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x  # [not win]
    max_pin: x.x.x  # [win]
  zlib:
    max_pin: x.x

# Pinning packages

# blas
libblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
libcblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapack:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapacke:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

abseil_cpp:
  - '20200225.2'
alsa_lib:
  - 1.2.3
arb:
  - '2.18'
arpack:
  - 3.7
arrow_cpp:
  - 1.0.1
aws_c_common:
  - 0.4.59
aws_c_event_stream:
  - 0.1.6
aws_checksums:
  - 0.1.10
aws_sdk_cpp:
  - 1.8.70
boost:
  - 1.74.0
boost_cpp:
  - 1.74.0
bzip2:
  - 1
cairo:
  - 1.16
cfitsio:
  - 3.470
cudnn:
  - 7.6.5
console_bridge:
  - 1.0
curl:
  - 7
dbus:
  - 1
expat:
  - 2.2
ffmpeg:
  - '4.3'
fftw:
  - 3
flann:
  - 1.9.1
fmt:
  - '7'
fontconfig:
  - 2.13
freetype:
  - 2
gazebo:
  - '11'
gf2x:
  - '1.3'
gdk_pixbuf:
  - 2
gnuradio_core:
  - 3.8.2
gsl:
  - 2.6
gstreamer:
  - 1.14.4
gst_plugins_base:
  - 1.14.4
gdal:
  - 3.0
geos:
  - 3.8.1
geotiff:
  - '1.6'
gflags:
  - 2.2
giflib:
  - 5.2
glew:
  - 2.1
glib:
  - 2.66
glog:
  - 0.4.0
glpk:
  - 4.65
gmp:
  - 6
google_cloud_cpp:
  - '1.20'
google_cloud_cpp_common:
  - 0.25.0
googleapis_cpp:
  - '0.10'
graphviz:
  - 2.38  # [win]
  - 2.40  # [not win]
grpc_cpp:
  - '1.33'
harfbuzz:
  - 2
hdf4:
  - 4.2
hdf5:
  - 1.10.5
icu:
  - 67
isl:
  - '0.22'
jasper:
  # the first windows build of jasper was 2.0.14
  - 1  # [not win]
  - 2  # [win]
jpeg:
  - 9
libjpeg_turbo:
  - 2
json_c:
  - 0.13
jsoncpp:
  - 1.8.4
kealib:
  - 1.4
krb5:
  - 1.17.1
libarchive:
  - 3.3
libblitz:
  - 0.10
libcurl:
  - 7
libcrc32c:
  - 1.1
libdap4:
  - 3.20.2
libevent:
  - 2.1.10
libffi:
  - 3.2
libgdal:
  - 3.0
libiconv:
  - 1.16
libkml:
  - 1.3
libmatio:
  - 1.5
libmicrohttpd:
  - 0.9
libnetcdf:
  - 4.7.4
libpcap:
  - '1.9'
libpng:
  - 1.6
libprotobuf:
  - 3.12
librdkafka:
  - '1.4'
librsvg:
  - 2
libsecret:
  - 0.18
libspatialindex:
  - 1.9.3
libssh2:
  - 1
libsvm:
  - 3.21
libtiff:
  - 4.1.0
libunwind:
  - 1
libv8:
  - 8.9.15
libwebp:
  - 1.1
libwebp_base:
  - 1.1
libxml2:
  - 2.9
libuuid:
  - 2.32.1
log4cxx:
  - 0.11.0
lz4_c:
  - 1.9.2
lzo:
  - 2
metis:
  - 5.1
mimalloc:
  - 1.6.3
mkl:
  - 2019
mpich:
  - 3.3
mpfr:
  - 4
mumps_mpi:
  - 5.2
mumps_seq:
  - 5.2
nccl:
  - 2.7.8.1
ncurses:
  - 6.2
netcdf_cxx4:
  - 4.3
netcdf_fortran:
  - 4.5
nettle:
  - 3.4
nss:
  - 3
nspr:
  - 4
nlopt:
  - 2.6.*
ntl:
  - '11.4.3'
# we build for the oldest version possible of numpy for forward compatibility
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.16   # [not (osx and arm64)]
  # - 1.16   # [not (osx and arm64)]
  # - 1.16   # [not (osx and arm64)]
  - 1.19   # [osx and arm64]
occt:
  - 7.4
ogre:
  - 1.10.12
openblas:
  - 0.3.*
opencv:
  - 4.5
openexr:
  - 2.5
openjpeg:
  - 2.3
openmpi:
  - 4.0
openssl:
  - 1.1.1
openturns:
  - '1.15'
orc:
  - 1.6.5
pango:
  - 1.42
pari:
  - 2.11
pcl:
  - 1.11.1
perl:
  - 5.26.2
petsc:
  - '3.13'
petsc4py:
  - '3.13'
slepc:
  - '3.13'
slepc4py:
  - '3.13'
pixman:
  - 0
poco:
  - 1.10.1
poppler:
  - '0.89'
proj:
  - 7.1.1
python:
  # part of a zip_keys: python, python_impl, numpy
  # - 3.6.* *_cpython    # [not (osx and arm64)]
  # - 3.7.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  # - cpython   # [not (osx and arm64)]
  # - cpython   # [not (osx and arm64)]
  - cpython
qt:
  - 5.12
re2:
  - 2020.11.01
readline:
  - 8.0
rocksdb:
  - "6.10"
root_base:
  - '6.22'
ruby:
  - 2.5
  - 2.6
r_base:
  - 3.6
  - 4.0
scotch:
  - 6.0.9
ptscotch:
  - 6.0.9
singular:
  - 4.1.2
snappy:
  - 1
soapysdr:
  - 0.7
sox:
  - 14.4.2
sqlite:
  - 3
suitesparse:
  - 5.6                # [not win]
  - 5.4                # [win]
tk:
  - 8.6                # [not ppc64le]
tiledb:
  - '2.1'
uhd:
  - 3.15.0
vc:                    # [win]
  - 14                 # [win]
vlfeat:
  - 0.9.20
vtk:
  - 8.2.0
x264:
  - 1!152.*
xerces_c:
  - 3.2
xrootd:
  - '5'
xz:
  - 5.2
zeromq:
  - 4.3.2
zlib:
  - 1.2
zstd:
  - 1.4


# Project overrides
macos_min_version:             # [osx]
  - 10.14                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.14                      # [osx]
