jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install vinca
      run: |
        pip install git+https://github.com/RoboStack/vinca.git

    - name: Generate recipes for Linux
      run: |
        git clean -fdx
        cp vinca_linux_64.yaml vinca.yaml
        vinca --multiple --platform linux-64
    - name: Generate azure pipelines for Linux
      run: |
        vinca-gha --platform linux-64 --trigger-branch buildbranch_linux -d ./recipes --additional-recipes
    - name: Commit files
      run: |
        if [[ -f "linux.yml" ]]; then
            mv linux.yml .github/workflows/
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add . -f
            git commit -m "Add build files `date '+%Y-%m-%d-%H%M'`" -a
            remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:buildbranch_linux --follow-tags --force
        fi
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GHA_PAT }}

    # Generate recipes for osx
    - name: Reset repo
      run: |
        git reset --hard origin/master
    - name: Generate recipes for macOS
      run: |
        git clean -fdx
        cp vinca_osx.yaml vinca.yaml
        vinca --multiple --platform osx-64
    - name: Generate azure pipelines for macOS
      run: |
        vinca-gha --platform osx-64 --trigger-branch buildbranch_osx -d ./recipes --additional-recipes
    - name: Commit files
      run: |
        if [[ -f "osx.yml" ]]; then
            mv osx.yml .github/workflows/
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add . -f
            git commit -m "Add build files `date '+%Y-%m-%d-%H%M'`" -a
            remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:buildbranch_osx --follow-tags --force
        fi
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GHA_PAT }}

    # Generate recipes for osx-arm64
    - name: Reset repo
      run: |
        git reset --hard origin/master
    - name: Generate recipes for macOS (arm64)
      run: |
        git clean -fdx
        cp vinca_osx_arm64.yaml vinca.yaml
        vinca --multiple --platform osx-arm64
    - name: Generate azure pipelines for macOS (arm64)
      run: |
        vinca-gha --platform osx-arm64 --trigger-branch buildbranch_osx_arm64 -d ./recipes --additional-recipes
    - name: Commit files
      run: |
        if [[ -f "osx_arm64.yml" ]]; then
            mv osx_arm64.yml .github/workflows/
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add . -f
            git commit -m "Add build files `date '+%Y-%m-%d-%H%M'`" -a
            remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:buildbranch_osx_arm64 --follow-tags --force
        fi
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GHA_PAT }}

    # Generate recipes for Windows
    - name: Reset repo
      run: |
        git reset --hard origin/master
    - name: Generate recipes for Windows
      run: |
        git clean -fdx
        cp vinca_win.yaml vinca.yaml
        vinca --multiple --platform win-64
    - name: Generate azure pipelines for Windows
      run: |
        vinca-gha --platform win-64 --trigger-branch buildbranch_win -d ./recipes --additional-recipes
    - name: Commit files for Windows
      run: |
        if [[ -f "win.yml" ]]; then
            mv win.yml .github/workflows/
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add . -f
            git commit -m "Add build files `date '+%Y-%m-%d-%H%M'`" -a
            remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:buildbranch_win --follow-tags --force
        fi
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GHA_PAT }}

    # Generate recipes for Linux ARM64
    - name: Reset repo
      run: |
        git reset --hard origin/master
    - name: Generate recipes for Linux ARM64
      run: |
        git clean -fdx
        cp vinca_linux_aarch64.yaml vinca.yaml
        vinca --multiple --platform linux-aarch64
    - name: Generate azure pipelines for Linux ARM64
      run: |
        vinca-gha --platform linux-aarch64 --trigger-branch buildbranch_linux_aarch64 -d ./recipes --additional-recipes -b 2
    - name: Commit files
      run: |
        if [[ -f "linux_aarch64.yml" ]]; then
            mv linux_aarch64.yml .github/workflows/build_linux_aarch64.yml
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add . -f
            git commit -m "Add build files `date '+%Y-%m-%d-%H%M'`" -a
            remote_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push "${remote_repo}" HEAD:buildbranch_linux_aarch64 --follow-tags --force
        fi
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GHA_PAT }}

on:
  push:
    branches:
      - master
      - main
